version: 2
jobs:
  build:

    docker:
      - image: elpaso/qgis-testing-environment:latest

    working_directory: /tests_directory/bkg-geocoder

    steps:

      - checkout


      - run:
          name: "Setup Environment Variables"
          command: |
            echo 'export DISPLAY=":99"' >> $BASH_ENV

      - run:
          name: "Setup QGIS Testing Environment"
          command: |
            qgis_setup.sh bkg-geocoder

      - run:
          name: "Run Unittests"
          command: |
            qgis_testrunner.sh bkg-geocoder.test.ci_tests
