version: 2
jobs:
  build:

    docker:
      - image: elpaso/qgis-testing-environment:latest

    working_directory: /tests_directory/bkg-geocoder

    steps:

      - checkout

      - run:
          name: Running X virtual framebuffer
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true

      #- run:
          #name: "Setup Environment Variables"
          #command: |
            #echo 'export DISPLAY=":99"' >> $BASH_ENV

      - run:
          name: "Setup QGIS Testing Environment"
          command: |
            qgis_setup.sh bkg-geocoder

      - run:
          name: "Run Unittests"
          user: root
          command: |
            export DISPLAY=":99"
            python3 test/ci_tests.py
