# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'featurepicker.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PickerDialog(object):
    def setupUi(self, PickerDialog):
        PickerDialog.setObjectName("PickerDialog")
        PickerDialog.resize(288, 284)
        self.verticalLayout = QtWidgets.QVBoxLayout(PickerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(PickerDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.review_layout = QtWidgets.QVBoxLayout()
        self.review_layout.setObjectName("review_layout")
        self.verticalLayout.addLayout(self.review_layout)
        self.line = QtWidgets.QFrame(PickerDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.results_label = QtWidgets.QLabel(PickerDialog)
        self.results_label.setObjectName("results_label")
        self.verticalLayout.addWidget(self.results_label)
        self.results_frame = QtWidgets.QFrame(PickerDialog)
        self.results_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.results_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.results_frame.setObjectName("results_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.results_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.results_area = QtWidgets.QScrollArea(self.results_frame)
        self.results_area.setWidgetResizable(True)
        self.results_area.setObjectName("results_area")
        self.results_widget = QtWidgets.QWidget()
        self.results_widget.setGeometry(QtCore.QRect(0, 0, 272, 206))
        self.results_widget.setObjectName("results_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.results_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.results_contents = QtWidgets.QGridLayout()
        self.results_contents.setObjectName("results_contents")
        self.verticalLayout_3.addLayout(self.results_contents)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.results_area.setWidget(self.results_widget)
        self.verticalLayout_2.addWidget(self.results_area)
        self.verticalLayout.addWidget(self.results_frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.accept_button = QtWidgets.QPushButton(PickerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accept_button.sizePolicy().hasHeightForWidth())
        self.accept_button.setSizePolicy(sizePolicy)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout.addWidget(self.accept_button)
        self.geom_only_button = QtWidgets.QPushButton(PickerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geom_only_button.sizePolicy().hasHeightForWidth())
        self.geom_only_button.setSizePolicy(sizePolicy)
        self.geom_only_button.setObjectName("geom_only_button")
        self.horizontalLayout.addWidget(self.geom_only_button)
        self.discard_button = QtWidgets.QPushButton(PickerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.discard_button.sizePolicy().hasHeightForWidth())
        self.discard_button.setSizePolicy(sizePolicy)
        self.discard_button.setObjectName("discard_button")
        self.horizontalLayout.addWidget(self.discard_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PickerDialog)
        QtCore.QMetaObject.connectSlotsByName(PickerDialog)

    def retranslateUi(self, PickerDialog):
        _translate = QtCore.QCoreApplication.translate
        PickerDialog.setWindowTitle(_translate("PickerDialog", "Ergebnisse inspizieren"))
        self.results_label.setText(_translate("PickerDialog", "Ergebnisse"))
        self.accept_button.setText(_translate("PickerDialog", "Übernehmen"))
        self.geom_only_button.setText(_translate("PickerDialog", "Nur verschieben"))
        self.discard_button.setText(_translate("PickerDialog", "Verwerfen"))
